export const allowedCategories = [
  {
    id: "halls",
    category: "halls",
  },
  {
    id: "decor",
    category: "decor",
  },
  {
    id: "artists",
    category: "artists",
  },
  {
    id: "clothing",
    category: "clothing",
  },
  {
    id: "photography",
    category: "photography",
  },
];

export const services = [
  {
    id: 1,
    name: "قاعة الفخامة",
    location: "الرياض",
    price: 5000,
    capacity: 300,
    rating: 4.5,
    type: "halls",
    image: "/pexels-bertellifotografia-17023018.jpg",
    description: "قاعة فاخرة للمناسبات الكبيرة",
  },
  {
    id: 2,
    name: "مصمم الأزياء أحمد",
    location: "جدة",
    price: 2000,
    rating: 4.8,
    type: "clothing",
    image: "/newOffers/pexels-alexander-mass-748453803-30934230.jpg",
    description: "تصميم أزياء فريدة للمناسبات الخاصة",
  },
  {
    id: 3,
    name: "استوديو التصوير الاحترافي",
    location: "الدمام",
    price: 3000,
    rating: 4.2,
    type: "photography",
    image: "/newOffers/pexels-yakup-polat-420882786-19698113.jpg",
    description: "توثيق لحظاتك بأعلى جودة",
  },
  {
    id: 4,
    name: "شركة ديكور الأحلام",
    location: "مكة",
    price: 4000,
    rating: 4.7,
    type: "decor",
    image: "/newOffers/pexels-istenci-30815990.jpg",
    description: "تحويل مناسبتك إلى حلم",
  },
  {
    id: 5,
    name: "فرقة النجوم الموسيقية",
    location: "المدينة",
    price: 6000,
    rating: 4.9,
    type: "artists",
    image: "/pexels-suvan-chowdhury-37305-144429.jpg",
    description: "إحياء مناسبتك بأجمل الألحان",
  },
];

export const servicesData = [
  {
    id: 1,
    name: "قاعة الفخامة",
    location: "الرياض",
    address: "شارع العليا، الرياض",
    price: 5000,
    capacity: 300,
    reviewCount: 124,
    rating: 4.5,
    type: "halls",
    amenities: ["واي فاي", "تكييف", "خدمة الطعام", "مواقف سيارات"],
    image: "/pexels-bertellifotografia-17023018.jpg",
    gallery: [
      "/pexels-bertellifotografia-17023018.jpg",
      "/pexels-bertellifotografia-17023018.jpg",
      "/pexels-bertellifotografia-17023018.jpg",
      "/pexels-bertellifotografia-17023018.jpg",
    ],
    description: "قاعة فاخرة للمناسبات الكبيرة",
    availability: [
      { date: "2024-07-20", slots: ["صباح", "مساء"] },
      { date: "2024-07-21", slots: ["بعد الظهر"] },
    ],
    reviews: [
      {
        id: 1,
        user: {
          name: "سارة",
          image: "/placeholder.svg?height=40&width=40",
          date: "2024-07-15",
        },
        rating: 5,
        title: "قاعة رائعة",
        comment: "كانت تجربة رائعة في هذه القاعة",
        helpful: 10,
        images: [],
      },
    ],
  },
  {
    id: 2,
    name: "مصمم الأزياء أحمد",
    location: "جدة",
    address: "شارع التحلية، جدة",
    price: 2000,
    reviewCount: 124,
    rating: 4.8,
    type: "clothing",
    amenities: ["تصميم فريد", "جودة عالية", "خدمة شخصية"],
    image: "/newOffers/pexels-alexander-mass-748453803-30934230.jpg",
    gallery: [
      "/newOffers/pexels-mlkbnl-10282410.jpg",
      "/newOffers/pexels-grish-petrosyan-3756797-15684451.jpg",
      "/newOffers/pexels-alexander-mass-748453803-30934230.jpg",
      "/newOffers/pexels-adeniuso-gomes-2148096772-30679836.jpg",
    ],
    description: "تصميم أزياء فريدة للمناسبات الخاصة",
    availability: [
      { date: "2024-07-20", slots: ["صباح", "مساء"] },
      { date: "2024-07-21", slots: ["بعد الظهر"] },
    ],
    reviews: [
      {
        id: 1,
        user: {
          name: "ليلى",
          image: "/placeholder.svg?height=40&width=40",
          date: "2024-07-10",
        },
        rating: 5,
        title: "تصميم رائع",
        comment: "أعجبني التصميم كثيراً",
        helpful: 5,
        images: [],
      },
    ],
  },
  {
    id: 3,
    name: "استوديو التصوير الاحترافي",
    location: "الدمام",
    address: "شارع الملك فهد، الدمام",
    price: 3000,
    reviewCount: 124,
    rating: 4.2,
    type: "photography",
    amenities: ["تصوير فيديو", "تصوير فوتوغرافي", "مونتاج"],
    image: "/newOffers/pexels-yakup-polat-420882786-19698113.jpg",
    gallery: [
      "/newOffers/pexels-yakup-polat-420882786-19698113.jpg",
      "/newOffers/pexels-yakup-polat-420882786-19698113.jpg",
      "/newOffers/pexels-skylake-17169148.jpg",
      "/newOffers/pexels-skylake-17169148.jpg",
    ],
    description: "توثيق لحظاتك بأعلى جودة",
    availability: [
      { date: "2024-07-20", slots: ["صباح", "مساء"] },
      { date: "2024-07-21", slots: ["بعد الظهر"] },
    ],
    reviews: [
      {
        id: 1,
        user: {
          name: "خالد",
          image: "/placeholder.svg?height=40&width=40",
          date: "2024-07-05",
        },
        rating: 4,
        title: "تصوير ممتاز",
        comment: "جودة التصوير عالية جداً",
        helpful: 7,
        images: [],
      },
    ],
  },
  {
    id: 4,
    name: "شركة ديكور الأحلام",
    location: "مكة",
    address: "شارع العزيزية، مكة",
    price: 4000,
    reviewCount: 124,
    rating: 4.7,
    type: "decor",
    amenities: ["تصميم داخلي", "تنسيق الزهور", "إضاءة"],
    image: "/newOffers/pexels-leeloothefirst-5038739.jpg",
    gallery: [
      "/newOffers/pexels-istenci-30815990.jpg",
      "/newOffers/pexels-istenci-30815990.jpg",
      "/newOffers/pexels-istenci-30815990.jpg",
      "/newOffers/pexels-istenci-30815990.jpg",
    ],
    description: "تحويل مناسبتك إلى حلم",
    availability: [
      { date: "2024-07-20", slots: ["صباح", "مساء"] },
      { date: "2024-07-21", slots: ["بعد الظهر"] },
    ],
    reviews: [
      {
        id: 1,
        user: {
          name: "نورة",
          image: "/placeholder.svg?height=40&width=40",
          date: "2024-07-01",
        },
        rating: 5,
        title: "ديكور رائع",
        comment: "الديكور كان مذهلاً",
        helpful: 12,
        images: [],
      },
    ],
  },
  {
    id: 5,
    name: "فرقة النجوم الموسيقية",
    location: "المدينة",
    address: "شارع سلطانة، المدينة",
    price: 6000,
    reviewCount: 124,
    rating: 4.9,
    type: "artists",
    amenities: ["موسيقى عربية", "موسيقى غربية", "إضاءة"],
    image: "/pexels-suvan-chowdhury-37305-144429.jpg",
    gallery: [
      "/pexels-suvan-chowdhury-37305-144429.jpg",
      "/pexels-suvan-chowdhury-37305-144429.jpg",
      "/pexels-suvan-chowdhury-37305-144429.jpg",
      "/pexels-suvan-chowdhury-37305-144429.jpg",
    ],
    description: "إحياء مناسبتك بأجمل الألحان",
    availability: [
      { date: "2024-07-20", slots: ["صباح", "مساء"] },
      { date: "2024-07-21", slots: ["بعد الظهر"] },
    ],
    reviews: [
      {
        id: 1,
        user: {
          name: "علي",
          image: "/placeholder.svg?height=40&width=40",
          date: "2024-06-25",
        },
        rating: 5,
        title: "فرقة ممتازة",
        comment: "أعجبني أداء الفرقة",
        helpful: 15,
        images: [],
      },
    ],
  },
];
